version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: terrakion-php
    volumes:
      - ./:/var/www
    networks:
      - terrakion-net

  webserver:
    image: nginx:alpine
    container_name: terrakion-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - terrakion-net

  db:
    image: mysql:8.0
    container_name: terrakion-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terrakion
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - terrakion-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: terrakion-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - terrakion-net

networks:
  terrakion-net:
    driver: bridge
